### ISSUE TITLE
Doesn't correctly parse functions with c++ custom return types and zero arguments

### ISSUE THREAD

**Issue by ghost** [JoshDreamland/JustDefineIt#10]
I discovered this in my reworking window_handle() ENIGMA pr. 

window_t is the return type of window_handle(), which has zero arguments...

In the LateralGM IDE, if I write `window_handle()` it compiles, using this code as to C-style typedef window_t:
```
#if GM_COMPATIBILITY_VERSION <= 81
typedef unsigned long long window_t;
#else
typedef void * window_t;
#endif 
```
In the LateralGM IDE, if I write `window_handle()` it doesn't compiles, using this code as to C++-style typedef window_t:
```
#if GM_COMPATIBILITY_VERSION <= 81
using window_t = unsigned long long;
#else
using window_t = void *;
#endif 
```

Instead, it says undefined reference to function `window_handle()`. The only way to make ENIGMA correctly compile the latter code, (the C++-style), typedef, is by removing the parenthesis and treating the function like a constant by writing `window_handle` instead to compile at all.

I don't know if this has already been fixed, as fundies informed me we have a version of JDI that's 2 years behind the current one under the enigma-dev repository.

**Comment by JoshDreamland** [comment]
JDI identifies the types to ENIGMA. The error you're describing is a (correct) linker error, generated by GCC.
