### ISSUE TITLE
Support expanding environment variables in strings passed to functions

### ISSUE THREAD

**Issue by ghost** [JoshDreamland/JustDefineIt#23]
This is something i'd like to be a checkbox in lateral/radialgm as an optional feature, and it will make strings slower but it will be good for projects which make heavy usage of environment variables so we won't have to constantly call environment_get_variable or c++ users wont have to getenv and concat a ton of times. It would be nice to have the option for having this done automatically

there could be an additional setting for whether to use $VARIABLE, %VARIABLE%. or ${VARIABLE} as those are only ways i've ever seen it done. Other options include if a variable isn't found whether to replace %VARIABLE%, etc with an empty string or leave it as-is. This i'm assuming is not something many people would want but it is a nice convenience for those who do need it.

Feel free to close this issue if you feel I'm beating a dead horse here.

**Comment by fundies** [comment]
This function exists in the compiler. https://github.com/enigma-dev/enigma-dev/blob/f93a3851fd987d96a7c8d3d381da95528854b29e/CompilerSource/settings.h#L108 Feel free to move it to shared/strings_util.h or whatever so you can access it in the engine too. You don't really need a lgm setting for this as you can just call escapeEnv(string)
